name: bctpay
description: An inclusive Fintech Payment App .

publish_to: "none"

version: 1.0.0+14

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # intro_slider: ^4.2.0
  introduction_screen: ^4.0.0
  google_fonts: ^6.2.1
  # otp_text_field: ^1.1.3
  pinput: ^5.0.0
  country_picker: ^2.0.26
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  http: ^1.2.1
  modal_progress_hud_nsn: ^0.5.1
  fluttertoast: ^8.2.12
  loading_animation_widget: ^1.2.1
  shared_preferences: ^2.2.3
  awesome_dialog: ^3.2.1
  # contacts_service: ^0.6.3
  qr_code_scanner: ^1.0.1
  # momo_vn: ^2.0.2
  iso8601_duration: ^1.2.1
  permission_handler: ^12.0.0+1
  # flutter_contacts: ^1.1.7+1
  # contacts_service: ^0.6.3
  fast_contacts: ^4.0.0
  currency_formatter: ^2.2.0
  another_flushbar: ^1.12.30
  dpad_container: ^2.0.4
  language_code: ^0.5.3+2
  image_picker: ^1.1.2
  file_selector: ^0.9.4
  path: ^1.8.3
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  share_plus: ^11.0.0
  screenshot: ^3.0.0
  path_provider: ^2.1.4
  document_file_save_plus: ^2.0.0
  webview_flutter: ^4.8.0
  flutter_dotenv: ^6.0.0
  country_flags: ^3.0.0
  cached_network_image: ^3.4.0
  encrypt: ^5.0.3
  tutorial_coach_mark: ^1.2.11
  local_auth: ^2.3.0
  local_auth_android: ^1.0.38
  local_auth_darwin: ^1.4.0
  currency_text_input_formatter: ^2.3.0
  qr_flutter: ^4.1.0
  connectivity_plus: ^6.0.4
  device_info_plus: ^11.1.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0
  # scan: ^1.6.0
  qr_code_tools: ^0.2.0
  firebase_crashlytics: ^5.0.1
  firebase_analytics: ^12.0.1
  flutter_staggered_animations: ^1.1.1
  flutter_local_notifications: ^19.3.0
  flutter_jailbreak_detection: ^1.10.0
  tuple: ^2.0.2
  crypto: ^3.0.3
  url_launcher: ^6.3.0
  # uni_links2: ^0.6.0+2
  scratcher: ^2.5.0
  pdf: ^3.11.1
  image_cropper: ^9.1.0
  camera: ^0.11.0+2
  camera_android_camerax: ^0.6.18+3
  google_mlkit_face_detection: ^0.4.0
  flutter_staggered_grid_view: ^0.7.0
  readmore: ^3.0.0
  package_info_plus: ^8.2.1
  lottie: ^3.2.0
  pull_to_refresh: ^2.0.0
  # fl_chart: ^0.70.2
  video_thumbnail: ^0.5.3
  video_player: ^2.9.3
  flutter_pdfview: ^1.4.0
  syncfusion_flutter_pdfviewer: ^31.1.17
  animated_text_kit: ^4.2.3
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.1
  test: ^1.25.15

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/whitelogo1024.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/whitelogo1024.png"
    background_color: "0xffffffff"
    theme_color: "0xffffffff"
  windows:
    generate: true
    image_path: "assets/images/whitelogo1024.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/whitelogo1024.png"

flutter:
  uses-material-design: true
  generate: true

  # flutter_assets:
  #   assets_path: assets/images/
  #   output_path: lib/globals/assets/
  #   package: module_home

  assets:
    - assets/images/
    - assets/lottie/
    - .env
    - .env.production
    - .env.development

flutter_intl:
  enabled: true
